language: python
python:
- '2.7'
env:
- DJANGO_VERSION=1.8.17
install:
- pip install -q Django==$DJANGO_VERSION
- pip install -r requirements.txt
script: nosetests
before_deploy: echo 'Starting deploy, hold onto something...'
deploy:
  provider: openshift
  user: rchapman83
  password:
    secure: dwMVlaUHoUFhtFfoED0QyyZZwdSuMJ1+M1aJIZm/7ug8wuxSuInFqfK5Oa7s23F2rB+XEAPQnwTdT4MnZMYTOX9kwRtlmqWj4+ous2Sfe8QEUiApEzxp5/zyYH2cW/kYah31za/Bu6jP4Tt0bKq+cCTQzeSRvSZHFq0Zn6Q+PKYwbgZy3p5OLmBGxhmlVQZW6ZTAg2VLN3cZxkumGgnJTWja3n2xoZJlONMxruznInhy7m28GT4U8wSCJknnOkNkP3OUlmqKRtnvsSK9UUinZvjiW645dD7uedj0M22FV1dIp2bGwZkdAY1l1oCUTlFKhoY0Xyo2rWsI6ZB21C4KAgJMGQstFuuUhBlTwRrmgFIDG9vj+eVXnlfS7EP2i0lz+H2GHTdD3/ACpGkZL9t2q6mEQOqQyzdwjg6ozUu7kgjxrEu4YY6CD5ussRY6nv5mr4rRLxqIB7O7YE3GCr9NnqHwwTNWZKawf82XgBvqtoZFoLXaLI6H4R7Bx9gWX2C1Du/UXQVskXIexjEvf7zxZjQqtiFbyS7m9hyGVHao1cbJah5OlivemE4IgMiMXbhXGkSwEpXIcfLNdeA1UMGDQXKKrtIIvHTGGp4sV6GBDhpoE854Fb6spPH/asyuzrg0CUwrTEzL53rCbctWzOSqKOHj6YKnxgQ9mT/zBSl9zro=
  app: personalweb
  domain: rchapman83
  on:
    repo: rchapman83/personal-web
branch: master
after_deploy: echo 'Fin'
notifications:
  email: false
branches:
  except:
  - legacy
  - experimental
  - dev
  only:
  - master
  - stable
