runtime: python311
env: standard
instance_class: B1
service: default
# Runtime configuration to use a specific operating system and runtime version in a flexible (flex) environment.
#runtime_config:
#    operating_system: 'ubuntu22'
#    runtime_version: '3.13'

env_variables:
  # GAE_INSTANCE can also be used as proj name
  PROJECT_NAME: $GOOGLE_CLOUD_PROJECT
  APP_VERSION: $GAE_VERSION
  # Make sure this is set to the same value as GAE_SERVICE to enable profiler
  APP_NAME: 'default'
  APP_MODULE: 'app:application'
  APP_PORT: '8080'
  FLASK_SECRET: 'seed'
  FLASK_SETTINGS: 'settings.py'
  GRAV_USER: 'rchapman83@gmail.com'
  GA_TRACKING_ID: '45321'
  GIT_REPO: 'zzzz/xxxx'
  GIT_TOKEN: '1243'
  
entrypoint: gunicorn --bind :$APP_PORT --workers 4 --threads 8 --timeout 0 $APP_MODULE

# This sample incurs costs to run on the App Engine flexible environment.
# The settings below are to reduce costs and are not appropriate for production use, unless you are a tightarse like me. 
#manual_scaling:
#  instances: 1
#resources:
#  cpu: 1
#  memory_gb: 0.5
#  disk_size_gb: 10

basic_scaling:
  max_instances: 1
  idle_timeout: 15m

#automatic_scaling:
#  min_num_instances: 1
#  max_num_instances: 2
#  cool_down_period_sec: 180
#  cpu_utilization:
#    target_utilization: 0.8
#  target_concurrent_requests: 100

# Liveness checks confirm that the VM and the Docker container are running. 
# Instances that are deemed unhealthy are restarted.
liveness_check:
  path: '/status'
  initial_delay_sec: 1200
  check_interval_sec: 30
  timeout_sec: 2
  failure_threshold: 3
  success_threshold: 2

readiness_check:
  path: '/status'
  check_interval_sec: 30
  timeout_sec: 2
  failure_threshold: 3
  success_threshold: 2
  app_start_timeout_sec: 900

# Sets a global default cache period for all static file handlers for an application. Default is 10mins
default_expiration: '1d 6h'

handlers:
  # This configures Google App Engine to serve the files in the app's static
  # directory.
- url: /app/static
  static_dir: static
  http_headers: 
    X-Forwarded-Proto: https
    X-Forwarded-For: clientIp
    X-Frame-Options: sameorigin
    X-XSS-Protection: 1; mode=block
    X-UA-Compatible: IE=edge
    Cache-Control: no-cache
    Referrer-Policy: same-origin
    Access-Control-Allow-Origin: https://www.rnchapman.pw, https://www.rnchapman.me

  # This handler routes all requests not caught above to your main app. It is
  # required when static routes are defined, but can be omitted (along with
  # the entire handlers section) when there are no static files defined.
- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301
  
error_handlers:
# Custom error pages that are returned for different error types so I know whats up.
  - file: default_error.html

  - error_code: over_quota
    file: over_quota.html

  - error_code: timeout
    file: timeout.html 
